version = 3.11.1

runner.dialect = scala213source3

maxColumn = 120
align.preset = most
align.stripMargin = true
continuationIndent.defnSite = 2

danglingParentheses.preset = true
newlines.afterCurlyLambda = preserve
spaces.inImportCurlyBraces = true

rewrite.rules = [
  Imports
  PreferCurlyFors,
  RedundantParens,
  RedundantBraces,
  SortModifiers
]
rewrite.imports.sort = scalastyle

docstrings.style = keep
docstrings.oneline = unfold

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
